### ISSUE TITLE
Replace cassava with a handwritten .janno parser

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#109]
In preparation for the CAA I [dived a bit](https://gist.github.com/nevrome/20186b9f02bbea3aa3a383cbdd3e57e1) into parsec and I think now, that we can achieve more precise parsing and - most importantly - better error reporting with a handwritten solution. Either with parsec or megaparsec.

This is not important for now, but a long-to-mid range goal

**Comment by stschiff** [comment]
Oh yes, parsec is great. Unfortunately for all the stream-processing happening in `sequence-formats` I had to use attoparsec because it's the one supported by the pipes framework (it sacrifices error message clarity for speed and is the one the pipes people have chosen to use).

But for anything happening inside of `poseidon-hs`, like Janno and Bibtex parsing, parsec would be good. What place did you have particularly in mind for this?

**Comment by nevrome** [comment]
I see - good to understand the reasoning behind your use of attoparsec!

As the title says I would like to replace cassava for janno parsing. Cassava fails for the whole row and gives pretty imprecise error messages. With parsec we could return better error messages and get rid of a dependency. 

I heard that megaparsec is particularly good with useful error messages, but I have no experiences with it yet. I also heard that parsec is a bit dead regarding new development, but maybe it's just already perfect. How bad can it be, if even pandoc relies on it?

**Comment by stschiff** [comment]
Ah sorry, didn't see the title. YES, I emphatically agree. I didn't dare to say something, because you implemented a pretty nice and working scheme with cassava, but if I would have done this I'd have used parsec for exactly that reason of having a bit more control over the error messages and stuff. So I definitely support this!

**Comment by nevrome** [comment]
Another thing one could theoretically solve with a custom parser is handling non-standard columns. Right now `forge` throws away all columns that are not defined in the Poseidon schema. A better implementation would probably be able to merge supplementary columns as well, setting them to `n/a` if they are missing in an input package.

**Comment by stschiff** [comment]
Good point!

**Comment by nevrome** [comment]
Cassava turned out to be more flexible and powerful than we thought back then. We now have helpful error messages for janno parsing on `--logMode VerboseLog`, e.g.

```
[Debug]   [12:55:59] Can't read sample in ./2010_RasmussenNature.janno in line 2: parse error (Failed reading: conversion error: Latitude "1169.2438" not between -90 and 90)
```

And we even have a mechanism to handle arbitrary additional .janno columns in forge since v1.1.6.0.

IMHO this issue is obsolete. If we run into more problems with .janno parsing, then we should check how we can further adjust cassava to our needs. So I close this now. Please reopen if you don't agree.
