### ISSUE TITLE
Redundancy of genoCheck in `validate`?

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#141]
https://github.com/poseidon-framework/poseidon-hs/blob/9368fd1b91cb33d36ed24e564d4de42dce31053e/src/Poseidon/CLI/Validate.hs#L67-L72

In my view, this is redundant, as we already perform such a check upon package reading if `_optGenoCheck` is set. @nevrome, you wrote the `validate` code, do you think we can indeed remove this?

Not too important of course...

**Comment by nevrome** [comment]
Hm - after investigating this odd duplication, I think I remember why it was implemented like this: The original idea was probably to catch the genotype exception and return a proper `Validation failed ✗` instead of only the nasty error message. But that doesn't work any more, now that this check is part of `readPoseidonPackageCollection`. So I guess we can remove the gimmick. I'll prepare a PR.
