### ISSUE TITLE
Support more genotype data formats

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#150]
The library could support some more genotype data formats (see e.g. [here](https://reich.hms.harvard.edu/software/InputFileFormats))
- [ ] ~ANCESTRYMAP~
- [x] EIGENSTRAT
- [ ] PED
- [x] PACKEDPED
- [ ] ~PACKEDANCESTRYMAP~
- [ ] VCF (see also https://github.com/poseidon-framework/poseidon2-schema/issues/45)
- [ ] ... ?

Would of course also require changes in the Poseidon schema.

**Comment by stschiff** [comment]
Hmm... I'm not sure with respect to ANCESTRYMAP and PACKEDANCESTRYMAP. I have never seen them elsewhere at all. I think in Poseidon we should stick to relatively well understood and widely used formats... of course, we could think about making it easier for users to pull in datasets from different formats, but I think in the package we should save them in Eigenstrat or Plink, as we had it, and maybe in the future VCF (although this will be a bit of a rabbit hole, because VCF allows for _so much_ richer data than the other two formats...)

**Comment by nevrome** [comment]
Adding new formats is a discussion that should start in the schema repository. And we already have an issue for that there: https://github.com/poseidon-framework/poseidon2-schema/issues/45

I'll close this one here now.
