### ISSUE TITLE
trident report

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#160]
I was thinking about priorities for Poseidon and concluded that web-based views on the published_data repo are probably pretty high up there. We have to avoid at all costs to get locked down in frontend development, but this list [here](https://poseidon-framework.github.io/#/public_repo) **just has to** be replaced with something that is more informative and useful. One possible solution could look like this: 

A new `trident` subcommand `report` could generate an html page with a nice view on the packages in `-d`. The output I have in mind is pretty similar to [this](https://getbootstrap.com/docs/5.1/examples/dashboard/#). Each package would be one element in the sitemap, and could be presented on its respective page with a table, a leaflet map and arbitrary plots (to be added later!).

For local package repos this is a fun toy to play with, but the real application is of course a website we could set up with the `report` output. A GitHub action in the published_data repo could run `report` on every change to the `master` and automatically update a `gh-pages` branch. Download links for the Poseidon server could be included here with `trident report -d . --addDownloadLinks`.

For the implementation we could try [lucid](https://hackage.haskell.org/package/lucid) and [lucid-extras](https://hackage.haskell.org/package/lucid-extras), which already has some support for bootstrap and leaflet. Or we start from scratch with one of [these](https://vrom911.github.io/blog/html-libraries). But I hope to keep this simple.

Usually I would have started to prepare a little prototype in a PR right away, but I know you have strong opinions here, @stschiff. And there are indeed many possible ways to tackle this. It's not necessary to make this a part of trident (which already is a bit bloated) and we don't even have to write it in Haskell. We also don't have to write code to run on a local package repo, but could instead query the Poseidon server for the relevant information. Maybe it's not even the best idea to write this ourselves :shrug:

**Comment by dhananjaya93** [comment]
Cant we convert Poseidon into JSON or XML format for web? It will be easier to deal with HTML and front end handling

**Comment by nevrome** [comment]
The [webserver](https://poseidon-framework.github.io/#/server) does provide JSON data. What do you suggest should we do with it? Are you suggesting to write a website in Javascript (or any other web language that is interpreted by the client) that displays the data from the server? If that's possible, then I guess that would be one of the many options we have to solve this.

Might be a fun idea to finally pick up some [Elm](https://elm-lang.org/) :thinking:. But I personally would be much faster implementing the `trident report` solution described above :man_shrugging:. And a static website would avoid potential performance issues a dynamic one might have.

**Comment by stschiff** [comment]
Well, first I agree with your priority. Just thinking from a salesman perspective, the current presentation of poseidon is quite dry, and the package list is less than minimal :-) Indeed.

Second, I like your idea of (dynamic and pretty) html reports per package, either generated by trident, or perhaps by an extra CLI or some functionality that even the server could generate on the fly. I mean... thinking back into the early times of the internet, that's exactly what a web-server would do: Serve html sites. 

In principle, there is a third option, and @dhananjaya93 hinted at it: Generate the website dynamically in the frontend using javascript. In that solution, the server perhaps wouldn't serve html, but JSON, and that would be built into a nice report dynamically.

I think, from a state-of-the-art perspective, the third option is what is typically done these days. However, as you said, that would mean we would have to dive at least a little bit into Vue (which is the backend behind docsify and compatible). I myself learned React.js (the main competitor of Vue.js) quite a bit... but I guess it's not rocket science. While perhaps involving a steeper learning curve in the beginning, it would be also easier to update and maintain, since then all the presentation stuff happens in the frontend, and we wouldn't have to constantly update the server software, just we'd like to prettify the report.

So, in the end it's a balance between pragmatism and design.

There is another reason, why I think most teams would opt for Option 3: With the setup you have in mind, @nevrome, you'd lock in the package concept quite deeply into the presentation. With dynamic javascript, we could easily add more meta-views on the entire repository, and filter functions, and so forth... more later, kids need to be brought into bed...

**Comment by stschiff** [comment]
You can actually add dynamic js via so-called cue components: https://docsify.js.org/#/vue

Perhaps I find the time to write a proof of concept element, like a dynamic indicator of the nr of packages to the website.

**Comment by nevrome** [comment]
Alright. I guess you're right and the client-side/frontend solution might be the typical way to solve this. Although I can not see, how `trident report` would limit us to any specific view on the data, I understand that a dynamic website is more modern and has a number of advantages. Especially in terms of extensibility.

But all my experiences with Javascript have been bad and I do not want to use it or maintain code written in it.

I assume you, @stschiff and @dhananjaya93, feel a lot more comfortable to go there :man_shrugging:. And Poseidon is big enough for all of us, so that's fine for me :slightly_smiling_face:

**Comment by stschiff** [comment]
I think `trident report` is a cool idea and could be followed up independently, and in fact potentially act as intermediate solution even.

**Comment by dhananjaya93** [comment]
My idea was running a `trident report` at back end and capture and covert data into JSON and passed into front end. I mean we dont need to do everything on a dynamic javascript front end. Stick to to our simple front end and use javascript functions and validations only in essential blocks. I dont have experience as a web developer but I like to try something as a learning.

**Comment by nevrome** [comment]
I think `trident report` could be an intermediate solution to the issue that people currently have to browse GitHub to see what data we have in the public repo (I got some feedback about that from @alexhbnr recently). So I will give it a try. But I'm fully aware that this is not the final solution for the website. Let's discuss this separately -- maybe on slack or in the website repo.

**Comment by nevrome** [comment]
We decided (for now) to generate a minimal static website with R. I implemented it here (https://github.com/poseidon-framework/published_data/pull/57) and on the master branch. The rendered website is now available at https://poseidon-framework.github.io/published_data

In the future we might switch to a more sophisticated setup.
