### ISSUE TITLE
`poseidon-http-server` should be generated in automatic release pipeline

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#219]
We currently only provide trident with each release, but actually I would want the server to be built as well. Most production server environments won't have the excessive RAM that is needed to actually build this, so I would rather want to download an executable. 

I had a look into the github actions, and it seems easy enough, but I'm not sure how much code duplication it requires. If I had to implement this quick and dirty I'd literally copy everything we have into a second release workflow targeting the server executable instead. Is there a more elegant way?

**Comment by nevrome** [comment]
I think that should generally work. The copy that builds the server can be a lot simpler actually, because we don't need macOS and Windows builds. If we would want to safe build time, then we could build trident and the server in one job. But that's a more radical change and I don't know if it's worth it.

**Comment by stschiff** [comment]
Not anymore critical. Server now compiles it.

**Comment by nevrome** [comment]
Solved in #234 with `trident serve`.
