### ISSUE TITLE
new feature janna-coalesce or janno-join

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#278]
We decided that a new feature is needed in trident, to merge janno files. The new command, e.g. named `trident janno-coalesce` would take a source-package and a target-package, match rows on the basis on an ID match (which could by default be using the PoseidonIDs in both packages, but alternatively would allow other janno-columns in the first and second file, similarly to other join-operation functions, e.g. in the tidyverse). It would then fill any fields missing in the target but filled in the source, and perhaps report warnings for conflicting information in the two janno files.

**Comment by nevrome** [comment]
A suggestion for the syntax:

```bash
trident jannocoalesce \
  --targetFile file/that/should/be/filled.janno \
  --sourceFile file/that/should/be/queried.janno \
  --outFile new/completed/file.janno \
  --fillColumns "Country,Latitude,Longitude,..." \ # (default: All)
  --overwriteColumns # default: False
```

1. `jannocoalesce`, because we already have `genoconvert` without a `-`
2. `--targetFile`, `--sourceFile` and `--outFile` are mandatory; `--outFile` can be identical to `--targetFile` (for brave people and automation)
3. `--fillColumns` defines the columns that should be merged; the default is to merge all overlapping columns
4. `--overwriteColumns` allows to overwrite the columns completely from the source, even if the target has some values filled; the default would be to preserve all available information in the target
5. Merging can only be done by `Poseidon_ID`; I think allowing to merge by other columns is pretty complex - if users want to do that they should use `qjanno` or the `janno` R package

**Comment by stschiff** [comment]
Very nice! I have some minor comments, but can be discussed after a first go. I hope to be able to get to it this week.

**Comment by nevrome** [comment]
1. is a good idea and 2. is indeed what I had in mind. For 3. I think we should not validate the output. There might be workflows where the user actually does not need a valid .janno file in the end. And for pipelines and automation it's probably better to keep the two steps clearly separate for error reporting.

**Comment by nevrome** [comment]
I close this now, because the discussion has moved to the concrete PR implementing the feature: https://github.com/poseidon-framework/poseidon-hs/pull/282
