### ISSUE TITLE
Update should also update the `lastModified` field

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#35]
`update`, `forge` and `init` should have correct `lastModified` fields, as well as checksums

**Comment by nevrome** [comment]
I implemented what I think is sensible in #29:

- `forge` and `init` do set the `lastModified` field to the current date, but do not add checksums as they are an advanced and optional feature mainly relevant for our central data archive.
- `update` does add/update checksums, but does not edit `lastModified`, because adding checksums is not per se a meaningful modification of the package

What do you think @stschiff?

**Comment by stschiff** [comment]
I think forge should in fact add checksums. We need to make their check optional, but there is no good reason why a forged package shouldn't have them, in my view

**Comment by nevrome** [comment]
You tend to be right about these things, but I'm not sure here. I fear the checksums will not be helpful, but annoying for users that are preparing their own datasets based on available packages with `forge`. 

I always envisioned the checksums to be only really relevant for our repository, where version-keeping is key. If we want to "force" them on the users for their own subsets, then we should have a good reason to do so. trident does not work with packages with broken checksums, so every tiny (!) change in the package files will require a subsequent call to `update` to bring the checksums back in sync! That will get frustrating soon if you're actively working with a dataset and not just preparing a static one for storage.

**Comment by stschiff** [comment]
You make a good argument. OK, let's leave things as they are for now. We could mid-term then think about renaming `update`, which sounds awfully relevant, when it actually "only" computes the checksums, which you are right can be seen as a bit of an arcane job...

**Comment by nevrome** [comment]
Renaming `update` is a good idea. Maybe `update-checksums` or simply `checksums`.
