### ISSUE TITLE
Automatic full validation before packaging in server

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#86]
The server should only provide fully validated packages, especially including the new genotype check in #85

**Comment by stschiff** [comment]
This is true. But it goes against my instinct to make server startup faster, not slower. Right now, due to the zip-packaging (which only happens once for an updated package, but still) and checksum validation, a server restart may take several minutes. That's annoying for deployment. 

I want to think whether we can run a pre-check as a separate command or so.

**Comment by nevrome** [comment]
Our infrastructure has changed over time and we now have the genotype data on GitHub's LFS. The validation GitHub action does still not check the genotype data, but we thoroughly scrutinize genotype data submissions in our review process.

I think it's not very likely that an issue slips through and has to be detected by the server. We can assume that the server only receives valid packages from GtiHub.

So I close this now. Please reopen if you think I'm wrong, @stschiff.
